version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /mnt/ntfs1/FILMS:/usr/src/app/movies 
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://backend:3000
    ports:
      - "3001:3001"
    depends_on:
      - backend